CREATE USER 'tank'@'localhost' IDENTIFIED WITH caching_sha2_password BY 'tank';
GRANT USAGE ON *.* TO 'tank'@'localhost';
ALTER USER 'tank'@'localhost' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;

GRANT SELECT, INSERT, UPDATE, DELETE, LOCK TABLES ON `tank`.* TO 'tank'@'localhost';
ALTER USER 'tank'@'localhost' ;
